{
  "Header": {
    "Original": "CVE-2022-2447 (A flaw was found in Keystone. There is a time lag (up to one hour in a ...)",
    "Line": 19298,
    "ID": "CVE-2022-2447",
    "Description": "(A flaw was found in Keystone. There is a time lag (up to one hour in a ...)"
  },
  "Annotations": [
    {
      "Original": "- python-keystonemiddleware 10.1.0-4 (bug #1021272)",
      "Line": 19299,
      "Type": "package",
      "Package": "python-keystonemiddleware",
      "Kind": "fixed",
      "Version": "10.1.0-4",
      "BugNo": 1021272
    },
    {
      "Original": "[bullseye] - python-keystonemiddleware \u003cno-dsa\u003e (Minor issue)",
      "Line": 19300,
      "Type": "package",
      "Release": "bullseye",
      "Package": "python-keystonemiddleware",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[buster] - python-keystonemiddleware \u003cno-dsa\u003e (Minor issue)",
      "Line": 19301,
      "Type": "package",
      "Release": "buster",
      "Package": "python-keystonemiddleware",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2105419",
      "Line": 19302,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2105419"
    },
    {
      "Original": "NOTE: https://review.opendev.org/c/openstack/keystonemiddleware/+/860481",
      "Line": 19303,
      "Type": "NOTE",
      "Description": "https://review.opendev.org/c/openstack/keystonemiddleware/+/860481"
    }
  ]
}