{
  "Header": {
    "Original": "CVE-2021-3514 (When using a sync_repl client in 389-ds-base, an authenticated attacke ...)",
    "Line": 102671,
    "ID": "CVE-2021-3514",
    "Description": "(When using a sync_repl client in 389-ds-base, an authenticated attacke ...)"
  },
  "Annotations": [
    {
      "Original": "- 389-ds-base 1.4.4.11-2 (bug #988727)",
      "Line": 102672,
      "Type": "package",
      "Package": "389-ds-base",
      "Kind": "fixed",
      "Version": "1.4.4.11-2",
      "BugNo": 988727
    },
    {
      "Original": "[buster] - 389-ds-base \u003cno-dsa\u003e (Minor issue)",
      "Line": 102673,
      "Type": "package",
      "Release": "buster",
      "Package": "389-ds-base",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[stretch] - 389-ds-base \u003cno-dsa\u003e (Minor issue)",
      "Line": 102674,
      "Type": "package",
      "Release": "stretch",
      "Package": "389-ds-base",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/389ds/389-ds-base/issues/4711",
      "Line": 102675,
      "Type": "NOTE",
      "Description": "https://github.com/389ds/389-ds-base/issues/4711"
    }
  ]
}