{
  "Header": {
    "Original": "CVE-2021-20272 (A flaw was found in privoxy before 3.0.32. An assertion failure could  ...)",
    "Line": 133111,
    "ID": "CVE-2021-20272",
    "Description": "(A flaw was found in privoxy before 3.0.32. An assertion failure could  ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2587-1}",
      "Line": 133112,
      "Type": "xref",
      "Bugs": [
        "DLA-2587-1"
      ]
    },
    {
      "Original": "- privoxy 3.0.32-1",
      "Line": 133113,
      "Type": "package",
      "Package": "privoxy",
      "Kind": "fixed",
      "Version": "3.0.32-1"
    },
    {
      "Original": "[buster] - privoxy 3.0.28-2+deb10u1",
      "Line": 133114,
      "Type": "package",
      "Release": "buster",
      "Package": "privoxy",
      "Kind": "fixed",
      "Version": "3.0.28-2+deb10u1"
    },
    {
      "Original": "NOTE: https://www.openwall.com/lists/oss-security/2021/02/28/1",
      "Line": 133115,
      "Type": "NOTE",
      "Description": "https://www.openwall.com/lists/oss-security/2021/02/28/1"
    },
    {
      "Original": "NOTE: https://www.privoxy.org/gitweb/?p=privoxy.git;a=commit;h=2256d7b4d67dd9c364386877d5af59943433458b",
      "Line": 133116,
      "Type": "NOTE",
      "Description": "https://www.privoxy.org/gitweb/?p=privoxy.git;a=commit;h=2256d7b4d67dd9c364386877d5af59943433458b"
    }
  ]
}